DROP TABLE IF EXISTS birds;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS trek;


CREATE TABLE birds (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    breed TEXT NOT NULL,
    age INTEGER NOT NULL
);

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    make TEXT NOT NULL,
    model TEXT NOT NULL, 
    man_year INTEGER NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE trek (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, 
    species TEXT NOT NULL,
    faction TEXT NOT NULL
);